apiVersion: v1
kind: Service
metadata:
  labels:
    name: go-ipam-restful
  name: go-ipam-restful
spec:
  ports:
    - name: http
      port: 9111
      protocol: TCP
      targetPort: http
  selector:
    name: go-ipam-restful
  type: ClusterIP
